name: 'Tmate to GitHub Actions'
author: 'zhengmz'
description: 'Connect to GitHub Actions VM via SSH for interactive debugging'
inputs:
  timeout:
    description: 'Timeout for connection'
    required: false
    default: '30'

runs:
  using: "composite"
  steps: 
    - uses: zhengmz/actions@lib

    - id: setup
      run: $GITHUB_ACTION_PATH/setup.sh
      shell: bash

    - name: Add environment variables
      env:
        TMATE_SOCK: ${{ steps.setup.outputs.TMATE_SOCK }}
        TMATE_SSH: ${{ steps.setup.outputs.TMATE_SSH }}
        TMATE_WEB: ${{ steps.setup.outputs.TMATE_WEB }}
      run: |
        echo "TMATE_SOCK=$TMATE_SOCK" >> $GITHUB_ENV
        echo "TMATE_SSH=$TMATE_SSH" >> $GITHUB_ENV
        echo "TMATE_WEB=$TMATE_WEB" >> $GITHUB_ENV
        echo "KEEP_FILE=/tmp/keepalive" >> $GITHUB_ENV
      shell: bash

    - name: Send tmate session to dingtalk
      if: ${{ env.DINGTALK_TOKEN != '' || env.DINGTALK_WEBHOOK != '' }}
      uses: zhengmz/actions@dingtalk
      with:
        token: ${{ env.DINGTALK_TOKEN }}
        webhook: ${{ env.DINGTALK_WEBHOOK }}
        secret: ${{ env.DINGTALK_SECRET }}
        keyword: ${{ env.DINGTALK_KEYWORD }}
        msgtype: 'markdown'
        content: |
          {
             "title": "Github Action Notify",
             "text": "# Github Action Notify \n ---- \n ## Repository \n > ${{ github.repositoryUrl }} \n > ref: ${{ github.ref_name }} \n  --- \n ## tmate session info \n - CLI: ${{ env.TMATE_SSH }} \n - WEB: <${{ env.TMATE_WEB }}> \n - Tips: Run 'touch ${{ env.KEEP_FILE }}' to keepalive or 'exit' to next step"
          }

    - run: $GITHUB_ACTION_PATH/wait.sh ${{ inputs.timeout }}
      shell: bash

branding:
  icon: 'terminal'
  color: 'gray-dark'
