name: 'Libs Actions'
author: 'zhengmz'
description: 'Shell Library for other action'
inputs:
  dist:
    description: 'dist file name for copying lib functions'
    type: string
    required: false
    default: '/tmp/functions'
outputs:
  functions:
    description: "Shell functions"
    value: ${{ steps.main.outputs.functions }}

runs:
  using: "composite"
  steps: 
    - id: main
      #run: source $GITHUB_ACTION_PATH/functions
      env:
        dist: ${{ inputs.dist }}
      run: |
        source $GITHUB_ACTION_PATH/functions
        if [[ -n "${dist}" ]]; then
          info "cp lib funtions to $dist..."
          cp $GITHUB_ACTION_PATH/functions ${dist}
        else
          warn "disable copying lib funtions."
        fi
        info "set output: cat functions and sed..."
        o="$(cat $GITHUB_ACTION_PATH/functions | sed ':a;N;s/\n/\\n/g;ta')"
        echo "::set-output name=functions::$o"
        info "success"
      shell: bash

branding:
  icon: 'book-open'
  color: 'blue'
