name: 'Libs Actions'
author: 'zhengmz'
description: 'Shell Library for other action'
outputs:
  functions:
    description: "Shell functions"
    value: ${{ steps.main.outputs.functions }}

runs:
  using: "composite"
  steps: 
    - id: main
      #run: source $GITHUB_ACTION_PATH/functions
      run: |
        o="$(cat $GITHUB_ACTION_PATH/functions | base64)"
        echo "::set-output name=functions::$o"
      shell: bash

branding:
  icon: 'book-open'
  color: 'blue'
