name: 'Libs Actions'
author: 'zhengmz'
description: 'Shell Library for other action'
outputs:
  functions:
    description: "Shell functions"
    value: ${{ steps.main.outputs.functions }}

runs:
  using: "composite"
  steps: 
    - id: main
      #run: source $GITHUB_ACTION_PATH/functions
      run: |
        source $GITHUB_ACTION_PATH/functions
        info "set output: cat functions and sed..."
        o="$(cat $GITHUB_ACTION_PATH/functions | sed ':a;N;s/\n/\\n/g;ta')"
        echo "::set-output name=functions::$o"
        info "success"
        echo "
          # Usage example:
          - name: Check functions by action
            env:
              f: steps.<id>.outputs.functions
            run: |
              echo \"\$f\" | sed 's/\\n/\n/g' > /tmp/functions
              source /tmp/functions
         "
      shell: bash

branding:
  icon: 'book-open'
  color: 'blue'
