#=================================================
# Description: ci for libs action
# Lisence: MIT
# Author: zhengmz
#=================================================

name: Lib CI

on: 
  push:
    branches:
      - 'lib'
    #paths:
    #  - '**/lib.yml'
    #  - 'functions'
    #  - 'action.yml'

  # Allows you to run this workflow manually from the Actions tab
  # Manual dispatch must be in the default branch.
  workflow_dispatch:
    inputs:
      delete_run:
        description: 'Delete older workflow run'
        type: boolean
        required: true
        default: 'true'

env:
  DELETE_OLD_RUN: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.delete_run || 'true' }}

jobs:
  build:
    runs-on: ubuntu-latest

    # For delete workflow
    permissions:
      actions: write

    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Get system infomation
      run: |
        #set +e
        echo "CPU: $(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c)"
        echo "UserName: $(whoami)"
        echo -e "SystemInfo: \n$(lsb_release  -a 2>&1 | grep -vi 'No LSB')\n"
        echo -e "Disk space: \n$(df -h)\n"
        echo -e "Environment: \n$(env)\n"
        echo "Github object json:"
        cat << EOF
          ${{ toJson(github) }}
        EOF

    - name: Load lib action
      id: lib
      uses: zhengmz/actions@lib

    - name: Check functions by action
      run: |
        #set +e
        ls -alh
        echo ${{ steps.lib.outputs.functions }}
        f=$(echo ${{ steps.lib.outputs.functions }} | base64 -d)
        echo $f > /tmp/functions
        cat /tmp/functions

    - name: Check functions by curl
      run: |
        #set +e
        ls -alh
        [ -f /tmp/functions ] && cat /tmp/functions && rm -f /tmp/functions
        curl -fsSL https://github.com/zhengmz/actions/raw/lib/functions > /tmp/functions
        source /tmp/functions
        info "information"
        warn "warning message"
        error "error log"
        log "notice"

    - name: Delete older workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      if: env.DELETE_OLD_RUN == 'true'
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 3
        delete_workflow_pattern: ${{ github.workflow }}

