#=================================================
# Description: ci for libs action
# Lisence: MIT
# Author: zhengmz
#=================================================

name: Lib CI

on: 
  push:
    branches:
      - 'lib'
    paths:
      - '**/lib.yml'
      - 'functions'
      - 'action.yml'

  # Be a reusable workflow
  workflow_call:
    inputs:
      delete_run:
        description: 'Delete older workflow run'
        #type: boolean
        type: string
        required: true
        default: 'true'
      import_mode:
        description: 'Import lib by action'
        #type: boolean
        type: string
        required: false
        default: 'action'
      dist_name:
        description: 'dist file name for copying lib functions'
        type: string
        required: false
    outputs:
      status:
        description: "The status of workflow"
        value: ${{ jobs.build.outputs.status }}

env:
  #DELETE_OLD_RUN: 'true'
  #IMPORT_ACTION: 'true'
  DELETE_OLD_RUN: ${{ inputs.delete_run || 'true' }}
  IMPORT_MODE: ${{ inputs.import_mode || 'action' }}

jobs:
  build:
    runs-on: ubuntu-latest

    # For delete workflow
    permissions:
      actions: write

    if: github.event.repository.owner.id == github.event.sender.id

    outputs:
      status: ${{ steps.check.outputs.status }}

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Get system infomation
      run: |
        #set +e
        echo "CPU: $(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c)"
        echo "UserName: $(whoami)"
        echo -e "SystemInfo: \n$(lsb_release  -a 2>&1 | grep -vi 'No LSB')\n"
        echo -e "Disk space: \n$(df -h)\n"
        echo -e "Environment: \n$(env)\n"
        #echo "Github object json:"
        #echo "${{ toJson(github) }}"

    - name: Import lib action
      if: env.IMPORT_MODE == 'action'
      id: lib
      uses: zhengmz/actions@lib
      with:
        dist_name: ${{ inputs.dist_name || '/tmp/functions' }}

    - name: Use lib functions
      id: check
      env:
        f: ${{ steps.lib.outputs.functions }}
      run: |
        #set +e
        ls -alh
        [ -f /tmp/functions ] && cat /tmp/functions && rm -f /tmp/functions
        if [ -n "$f" ]; then
          echo "$f" | sed 's/\\n/\n/g' > /tmp/functions
        else
          curl -fsSL https://github.com/zhengmz/actions/raw/lib/functions > /tmp/functions
        fi
        source /tmp/functions
        info "information"
        warn "warning message"
        error "error log"
        log "notice"
        echo "::set-output name=status::success"

    - name: Delete older workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      if: env.DELETE_OLD_RUN == 'true'
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 3
        delete_workflow_pattern: ${{ github.workflow }}

