#=================================================
# Description: ci for libs action
# Lisence: MIT
# Author: zhengmz
#=================================================

name: Lib CI

on: 
  push:
    branches:
      - 'lib'
    paths:
      - '**/lib.yml'
      - 'functions'
      - 'action.yml'

  # Be a reusable workflow
  workflow_call:
    inputs:
      import_mode:
        description: 'Import lib by action'
        #type: boolean
        type: string
        required: false
        default: 'action'
      dist:
        description: 'dist file name for copying lib functions'
        type: string
        required: false
    outputs:
      status:
        description: "The status of workflow"
        value: ${{ jobs.build.outputs.status }}

env:
  #DELETE_OLD_RUN: 'true'
  #IMPORT_ACTION: 'true'
  DELETE_OLD_RUN: ${{ github.event_name == 'workflow_dispatch' && 'false' || 'true' }}
  IMPORT_MODE: ${{ inputs.import_mode || 'action' }}
  DIST_NAME: ${{ inputs.dist || '/tmp/functions' }}

jobs:
  build:
    runs-on: ubuntu-latest

    # For delete workflow
    permissions:
      actions: write

    if: github.event.repository.owner.id == github.event.sender.id

    outputs:
      status: ${{ steps.check.outputs.status }}

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Get system infomation
      run: |
        #set +e
        echo "CPU: $(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c)"
        echo "UserName: $(whoami)"
        echo -e "SystemInfo: \n$(lsb_release  -a 2>&1 | grep -vi 'No LSB')\n"
        echo -e "Disk space: \n$(df -h)\n"
        #echo -e "Environment: \n$(env)\n"
        echo -e "Github Environment: \n$(env | grep GITHUB)\n"
        echo -e "Runner Environment: \n$(env | grep RUNNER)\n"
        echo "Github object json: ${{ toJson(github) }}"
        echo "job object json: ${{ toJson(job) }}"
        echo "inputs object json: ${{ inputs != '' && toJson(inputs)  || ''}}"

    - name: Import lib action
      if: env.IMPORT_MODE == 'action'
      id: lib
      uses: zhengmz/actions@lib
      with:
        dist: ${{ env.DIST_NAME }}

    - name: Use lib functions
      id: check
      env:
        f: ${{ steps.lib.outputs.functions }}
        dist: ${{ env.DIST_NAME }}
      run: |
        #set +e
        ls -alh
        [ -n "$dist" -a -f $dist ] && cat $dist && rm -f $dist
        if [ -n "$f" ]; then
          echo "$f" | sed 's/\\n/\n/g' > $dist
        else
          curl -fsSL https://github.com/zhengmz/actions/raw/lib/functions > $dist
        fi
        source $dist
        info "information"
        warn "warning message"
        error "error log"
        log "notice"
        echo "::set-output name=status::success"

    - name: Delete older workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      #if: env.DELETE_OLD_RUN == 'true' && github.event_name != 'workflow_dispatch'
      if: env.DELETE_OLD_RUN == 'true'
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 3
        delete_workflow_pattern: ${{ github.workflow }}

