#=================================================
# Description: ci for libs action
# Lisence: MIT
# Author: zhengmz
#=================================================

name: Lib CI

on: 
  push:
    branches:
      - 'lib'
    paths:
      - '**/lib.yml'
      - 'functions'
      - 'action.yml'

env:
  DELETE_OLD_RUN: 'true'
  IMPORT_ACTION: 'true'

jobs:
  build:
    runs-on: ubuntu-latest

    # For delete workflow
    permissions:
      actions: write

    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Get system infomation
      run: |
        #set +e
        echo "CPU: $(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c)"
        echo "UserName: $(whoami)"
        echo -e "SystemInfo: \n$(lsb_release  -a 2>&1 | grep -vi 'No LSB')\n"
        echo -e "Disk space: \n$(df -h)\n"
        echo -e "Environment: \n$(env)\n"
        echo "Github object json:"
        cat << EOF
          ${{ toJson(github) }}
        EOF

    - name: Import lib action
      if: env.IMPORT_ACTION == 'true'
      id: lib
      uses: zhengmz/actions@lib

    - name: Check functions
      env:
        f: ${{ steps.lib.outputs.functions }}
      run: |
        #set +e
        ls -alh
        [ -f /tmp/functions ] && cat /tmp/functions && rm -f /tmp/functions
        if [ -n "$f" ]; then
          echo "$f" | sed 's/\\n/\n/g' > /tmp/functions
        else
          curl -fsSL https://github.com/zhengmz/actions/raw/lib/functions > /tmp/functions
        fi
        source /tmp/functions
        info "information"
        warn "warning message"
        error "error log"
        log "notice"

    - name: Delete older workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      if: env.DELETE_OLD_RUN == 'true'
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 3
        delete_workflow_pattern: ${{ github.workflow }}

