#=================================================
# Description: Manually run a ci workflow
# Lisence: MIT
# Author: zhengmz
#=================================================

name: Manual CI

on: 
  # Allows you to run this workflow manually from the Actions tab
  # Manual dispatch must be in the default branch.
  workflow_dispatch:
    inputs:
      workflow:
        description: 'Delete older workflow run'
        type: choice
        required: true
        default: 'lib'
        options:
          - lib
          - dingtalk
          - lib2
      delete_run:
        description: 'Delete older workflow run'
        type: boolean
        required: true
        default: true

env:
  DELETE_OLD_RUN: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.delete_run || 'true' }}

jobs:
  # Reusing sub workflow
  call-lib-yml:
    uses: zhengmz/actions/.github/workflows/lib.yml@lib
    if: github.event.inputs.workflow == 'lib'
    with:
      delete_run: ${{ github.event.inputs.delete_run }}
      dist_name: ".functions"

  call-dingtalk-yml:
    uses: zhengmz/actions/.github/workflows/dingtalk.yml@dingtalk
    if: github.event.inputs.workflow == 'dingtalk'
    secrets: inherit
    with:
      msgtype: "text"
      content: |
        {
            "content": "我就是我, 是不一样的烟火"
        }
      #msgtype: "markdown"
      #content: |
      #  {
      #    "title":"杭州天气",
      #    "text": "#### 杭州天气 @150XXXXXXXX \n > 9度，西北风1级，空气良89，相对温度73%\n > ![screenshot](https://img.alicdn.com/tfs/TB1NwmBEL9TBuNjy1zbXXXpepXa-2400-1218.png)\n > ###### 10点20分发布 [天气](https://www.dingtalk.com) \n"
      #  }
      at: "all"
      ignore_error: "false"

  build:
    runs-on: ubuntu-latest

    #needs: call-lib-yml

    # For delete workflow
    permissions:
      actions: write

    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Get system infomation
      run: |
        #set +e
        echo "CPU: $(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c)"
        echo "UserName: $(whoami)"
        echo -e "SystemInfo: \n$(lsb_release  -a 2>&1 | grep -vi 'No LSB')\n"
        echo -e "Disk space: \n$(df -h)\n"
        echo -e "Environment: \n$(env)\n"
        echo "Github object json:"
        cat << EOF
          ${{ toJson(github) }}
        EOF

    # compare reusing workflow, gh cli have two disadvantage
    #   - lib2.yml must be in same branch with this yml file
    #   - and without visual process
    - name: Run workflow lib2.yml
      if: github.event.inputs.workflow == 'lib2'
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        set +e
        #echo ${{ github.token }} | gh auth login --with-token
        gh workflow run ${{ github.event.inputs.workflow }}.yml -f delete_run=$DELETE_OLD_RUN

    - name: Delete older workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      if: env.DELETE_OLD_RUN == 'true'
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 3
        delete_workflow_pattern: ${{ github.workflow }}

